import OpenAI from "openai";
import { CaptionStyle } from "@shared/schema";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

interface GenerateCaptionsOptions {
  imageBase64: string;
  style: CaptionStyle;
  context?: string;
  fileName: string;
}

const stylePrompts: Record<CaptionStyle, string> = {
  professional: "Create professional, polished captions suitable for business or corporate use. Focus on credibility, expertise, and achievement.",
  friendly: "Create warm, approachable captions with an inviting tone. Use conversational language that feels personal and welcoming.",
  funny: "Create humorous, witty captions that are clever and entertaining. Use playfulness and light-hearted humor.",
  minimalist: "Create ultra-concise, impactful captions with minimal words. Focus on brevity and essential meaning.",
  inspirational: "Create uplifting, motivational captions that inspire and encourage. Use positive, empowering language.",
  casual: "Create relaxed, laid-back captions with everyday language. Keep it natural and unforced.",
};

export async function generateCaptions({
  imageBase64,
  style,
  context,
  fileName,
}: GenerateCaptionsOptions): Promise<string[]> {
  const styleInstruction = stylePrompts[style];
  const contextInstruction = context 
    ? `\n\nAdditional context about the image: ${context}` 
    : "";

  const systemPrompt = `You are an expert social media caption writer. ${styleInstruction}

Generate exactly 3 different caption variations for the provided image. Each caption should be unique and creative.

${style === "minimalist" ? "Keep each caption to 5 words or less." : "Keep captions concise but engaging, typically 1-2 sentences."}

Return ONLY the 3 captions, one per line, with no numbering, bullets, or additional text.${contextInstruction}`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "user",
          content: [
            {
              type: "text",
              text: systemPrompt,
            },
            {
              type: "image_url",
              image_url: {
                url: imageBase64,
                detail: "auto",
              },
            },
          ],
        },
      ],
      max_tokens: 300,
      temperature: 0.8,
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new Error("No captions generated by AI");
    }

    const captions = content
      .split("\n")
      .map(line => line.trim())
      .filter(line => line.length > 0)
      .slice(0, 3);

    if (captions.length === 0) {
      throw new Error("Failed to parse captions from AI response");
    }

    // Ensure we always have 3 captions
    while (captions.length < 3) {
      captions.push(captions[0] || "Great moment captured!");
    }

    return captions.slice(0, 3);
  } catch (error) {
    console.error(`Error generating captions for ${fileName}:`, error);
    
    // Provide more helpful error messages
    if (error instanceof Error) {
      if (error.message.includes('image')) {
        throw new Error(`Unable to process image: ${fileName}. The image may be corrupted or in an unsupported format.`);
      }
      throw new Error(`Caption generation failed: ${error.message}`);
    }
    throw error;
  }
}

export async function generateCaptionsForMultipleImages(
  images: Array<{ base64: string; fileName: string }>,
  style: CaptionStyle,
  context?: string
): Promise<Array<{ fileName: string; captions: string[] }>> {
  const limit = pLimit(3);

  const results = await Promise.all(
    images.map((image, index) =>
      limit(async () => {
        try {
          const captions = await generateCaptions({
            imageBase64: image.base64,
            style,
            context,
            fileName: image.fileName,
          });
          return { fileName: image.fileName, captions, index };
        } catch (error) {
          console.error(`Failed to generate captions for ${image.fileName}:`, error);
          return { 
            fileName: image.fileName, 
            captions: [`Unable to generate caption for this image.`],
            index 
          };
        }
      })
    )
  );

  return results.sort((a, b) => a.index - b.index);
}

function pLimit(concurrency: number) {
  const queue: Array<() => void> = [];
  let activeCount = 0;

  const next = () => {
    activeCount--;
    if (queue.length > 0) {
      queue.shift()!();
    }
  };

  const run = async <T>(fn: () => Promise<T>): Promise<T> => {
    activeCount++;
    const result = await fn();
    next();
    return result;
  };

  const enqueue = <T>(fn: () => Promise<T>): Promise<T> => {
    return new Promise<T>((resolve, reject) => {
      const execute = () => {
        run(fn).then(resolve, reject);
      };

      if (activeCount < concurrency) {
        execute();
      } else {
        queue.push(execute);
      }
    });
  };

  return enqueue;
}
